"use strict";
const header=document.querySelector(".header"),menuBtn=document.getElementById("menuBtn"),navLinks=document.getElementById("navLinks"),toast=document.getElementById("toast"),closeToast=document.getElementById("closeToast"),loader=document.getElementById("loader"),scrollProgress=document.getElementById("scrollProgress"),cursorGlow=document.getElementById("cursorGlow"),lightbox=document.getElementById("lightbox"),lightboxClose=document.getElementById("lightboxClose"),lightboxImage=document.getElementById("lightboxImage"),lightboxTitle=document.getElementById("lightboxTitle"),prefersReducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
const yearElement=document.getElementById("year");if(yearElement)yearElement.textContent=new Date().getFullYear();
function hideLoader(){if(!loader||loader.classList.contains("hidden"))return;loader.classList.add("hidden");setTimeout(()=>loader.style.display="none",700)}window.addEventListener("load",()=>setTimeout(hideLoader,prefersReducedMotion?100:1100));setTimeout(hideLoader,3500);
function updateScrollEffects(){const t=window.scrollY||document.documentElement.scrollTop;if(header)header.classList.toggle("scrolled",t>15);if(scrollProgress){const e=document.documentElement.scrollHeight-document.documentElement.clientHeight;scrollProgress.style.width=`${e>0?t/e*100:0}%`}}updateScrollEffects();window.addEventListener("scroll",updateScrollEffects,{passive:true});
function openMenu(){if(!navLinks||!menuBtn)return;navLinks.classList.add("open");menuBtn.classList.add("active");menuBtn.setAttribute("aria-expanded","true")}function closeMenu(){if(!navLinks||!menuBtn)return;navLinks.classList.remove("open");menuBtn.classList.remove("active");menuBtn.setAttribute("aria-expanded","false")}
menuBtn?.addEventListener("click",e=>{e.stopPropagation();navLinks?.classList.contains("open")?closeMenu():openMenu()});navLinks?.querySelectorAll("a").forEach(a=>a.addEventListener("click",closeMenu));document.addEventListener("click",e=>{if(navLinks&&menuBtn&&navLinks.classList.contains("open")&&!navLinks.contains(e.target)&&!menuBtn.contains(e.target))closeMenu()});
let toastTimer;function showToast(){if(!toast)return;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),4500)}function hideToast(){if(!toast)return;toast.classList.remove("show");clearTimeout(toastTimer)}document.querySelectorAll(".download-link").forEach(a=>a.addEventListener("click",showToast));closeToast?.addEventListener("click",hideToast);
const revealElements=document.querySelectorAll(".reveal");if(prefersReducedMotion||!("IntersectionObserver" in window))revealElements.forEach(e=>e.classList.add("visible"));else{const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");o.unobserve(e.target)}}),{threshold:.12,rootMargin:"0px 0px -40px 0px"});revealElements.forEach(e=>o.observe(e))}
const pageSections=document.querySelectorAll("main section[id], header[id]"),navigationLinks=document.querySelectorAll('.nav-links a[href^="#"]');function setActiveNavigation(){let e="home",t=window.scrollY+160;pageSections.forEach(s=>{if(t>=s.offsetTop)e=s.id});navigationLinks.forEach(a=>a.classList.toggle("active",a.getAttribute("href")?.replace("#","")===e))}setActiveNavigation();window.addEventListener("scroll",setActiveNavigation,{passive:true});
function animateCounter(c){const target=Number(c.dataset.target)||0;if(prefersReducedMotion){c.textContent=target;return}const d=1400,s=performance.now();function u(n){const p=Math.min((n-s)/d,1),e=1-Math.pow(1-p,3);c.textContent=Math.floor(target*e);p<1?requestAnimationFrame(u):c.textContent=target}requestAnimationFrame(u)}const counters=document.querySelectorAll(".counter");if(counters.length&&"IntersectionObserver" in window){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){animateCounter(e.target);o.unobserve(e.target)}}),{threshold:.5});counters.forEach(c=>o.observe(c))}else counters.forEach(animateCounter);
function openLightbox(src,title){if(!lightbox||!lightboxImage||!lightboxTitle)return;lightboxImage.src=src;lightboxImage.alt=`${title} screenshot`;lightboxTitle.textContent=title;lightbox.classList.add("open");lightbox.setAttribute("aria-hidden","false");document.body.classList.add("lightbox-open")}function closeLightbox(){if(!lightbox)return;lightbox.classList.remove("open");lightbox.setAttribute("aria-hidden","true");document.body.classList.remove("lightbox-open");setTimeout(()=>{if(lightboxImage)lightboxImage.src=""},300)}document.querySelectorAll(".screen-card").forEach(card=>{const b=card.querySelector(".view-image");b?.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();if(card.dataset.image)openLightbox(card.dataset.image,card.dataset.title||"PharmaStock Pro")})});lightboxClose?.addEventListener("click",closeLightbox);lightbox?.addEventListener("click",e=>{if(e.target===lightbox)closeLightbox()});document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeMenu();closeLightbox();hideToast()}});
if(cursorGlow&&!prefersReducedMotion&&window.matchMedia("(pointer: fine)").matches){let tx=0,ty=0,cx=0,cy=0;document.addEventListener("mousemove",e=>{tx=e.clientX;ty=e.clientY;cursorGlow.classList.add("visible")},{passive:true});document.addEventListener("mouseleave",()=>cursorGlow.classList.remove("visible"));(function a(){cx+=(tx-cx)*.14;cy+=(ty-cy)*.14;cursorGlow.style.transform=`translate3d(${cx}px,${cy}px,0)`;requestAnimationFrame(a)})()}
const dashboardImage=document.querySelector(".app-window .window-image img");dashboardImage?.addEventListener("error",()=>{const c=dashboardImage.closest(".window-image"),p=document.querySelector(".app-window .placeholder");if(c)c.style.display="none";if(p)p.style.display="grid"});document.querySelectorAll(".screen-card img").forEach(img=>img.addEventListener("error",()=>{const c=img.closest(".screen-image");if(!c)return;img.style.display="none";c.classList.add("image-missing");if(!c.querySelector(".missing-image-message")){const m=document.createElement("div");m.className="missing-image-message";m.innerHTML="<b>Screenshot unavailable</b><span>Check the image name in the assets folder.</span>";c.appendChild(m)}}));window.addEventListener("resize",()=>{if(window.innerWidth>1000)closeMenu()});
